### ISSUE TITLE
Need for strftime tutorial resource to focus lab learning on ERB

### ISSUE THREAD

**Issue by michaelwahlin** [learn-co-curriculum/sinatra-views-lab#14]
--> Using ERB tags, and the DateTime library, display today's date in a p tag. The date should be formatted to look something like this The date is Wednesday, November 18, 2015.

In this lab it would be helpful to list a tutorial resource on strftime.  I felt like I spent more time figuring that part out than completing the rest of the lab.  Thanks!

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
